language: cpp
sudo: false
dist: trusty
compiler:
- gcc
- clang
os:
- linux
git:
  submodules: false
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- sed -i 's/https:\/\/github.com/https:\/\/'"$CI_USER_TOKEN"'@github.com/' .gitmodules
- git submodule update --init --recursive
install: make cmake
script:
- mkdir build
- cd build
- cmake ..
branches:
  only:
  - master
notifications:
  email: false