language: cpp
dist: trusty
compiler:
- gcc
os:
- linux
install: make cmake
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- mkdir build
- cd build
- cmake ..
script: make
branches:
  only:
  - master
notifications:
  email: false