language: cpp
sudo: false
dist: trusty
compiler:
- gcc
- clang
os:
- linux
- osx
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install: make cmake
script:
- mkdir build
- cd build
- cmake ..
branches:
  only:
  - master
notifications:
  email: false