language: cpp
sudo: false
dist: trusty
os:
- linux
matrix:
  exclude:
    - os: linux
      compiler: gcc
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:            
            - llvm-toolchain-trusty
          packages:
            - clang-3.9
      env: COMPILER=clang++-3.9
git:
  submodules: false
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
- sed -i 's/https:\/\/github.com/https:\/\/'"$CI_USER_TOKEN"'@github.com/' .gitmodules
- git submodule update --init --recursive
install: true
script:
- mkdir build
- cd build
- cmake ..
- make
branches:
  only:
  - master
notifications:
  email: false